### ISSUE TITLE
disable mime checking in frontend

### ISSUE THREAD

**Issue by asyncfncom** [metric-space-ai/octopus_client#24]
When I try to upload this plugin https://github.com/metric-space-ai/octopus_function/blob/main/information_retrieval.py
I get an error
"An incorrect file has been selected for the selected file. format:information_retrieval.py _ type: The expected format is "*.py" and valid type is "text/x-python""

Please disable mime checking on frontend. We do code checks on backend side.

**Comment by cyrusnej** [comment]
Done
