### ISSUE TITLE
don't allow to configure services with malicious code

### ISSUE THREAD

**Issue by asyncfncom** [metric-space-ai/octopus_client#42]
After uploading a service you can move to configuration step only in a situation when service has status "configuration". If service has status "malicious_code_detected" than you can not show to user configuration step. If user tries to configure service with status "malicious_code_detected" than API returns conflicting request.

If malicious code is detected than user should be able to reupload service (update request https://api.octopus-ai.app/swagger-ui/#/ai_services/update) . You can implement this after implementing this task https://github.com/metric-space-ai/octopus_client/issues/34

I think that there should be some kind of warning popup "The code that you try to upload may contain some malicious fragments" @mkh-welsch ?

**Comment by cyrusnej** [comment]
Done
