### ISSUE TITLE
use new endpoint to extract meta info from WASP app

### ISSUE THREAD

**Issue by asyncfncom** [metric-space-ai/octopus_client#45]
@mkh-welsch thinks it's too complicated for user to provide title and description for WASP app when he uploads it.

Here is a new endpoint
https://api.preview.octopus-ai.app/swagger-ui/#/wasp_apps/extract_meta
You need to upload there ZIP archive and it will return title and description of the WASP app.

Use this to prefil title and description for WASP app in frontend app. User can always edit it, but giving such prefiled values will make frontend more user friendly.

**Comment by cyrusnej** [comment]
Done
