### ISSUE TITLE
setup screen doesn't work correctly

### ISSUE THREAD

**Issue by asyncfncom** [metric-space-ai/octopus_client#47]
I deployed a new system. When I visited https://likora.octopus-ai.app I was redirected to login screen.

<img width="960" alt="screen" src="https://github.com/metric-space-ai/octopus_client/assets/136445484/3b855d28-b206-4d10-875f-d1b3cb6f1cb8">

This is not a correct behaviour, because https://api.octopus-ai.app/swagger-ui/#/setup/info returns

```
{
    "setup_required": true
}
```

So I should see a setup screen.

**Comment by cyrusnej** [comment]
Done
