### ISSUE TITLE
parameter edit doesn't work

### ISSUE THREAD

**Issue by asyncfncom** [metric-space-ai/octopus_client#52]
I can not edit parameter value
<img width="960" alt="screen" src="https://github.com/metric-space-ai/octopus_client/assets/136445484/83e3c7ad-d0b7-4ef2-9464-e8e250d8964e">

**Comment by asyncfncom** [comment]
done

**Comment by asyncfncom** [comment]
It looks like @mkh-welsch can not edit system prompt

**Comment by cyrusnej** [comment]
Done
