### ISSUE TITLE
show audio player

### ISSUE THREAD

**Issue by asyncfncom** [metric-space-ai/octopus_client#63]
Please show audio player for audio attachment.

When you will have a file with media_type = 'audio/aac' like the one below

```
                  id                  |           chat_message_id            |                file_name                 | media_type |       created_at       | deleted_at |            original_file_name
--------------------------------------+--------------------------------------+------------------------------------------+------------+------------------------+------------+------------------------------------------
 4710a207-222f-46b9-9d8f-1e7921d1ee6a | 79d0272c-198d-4475-a7d7-cb7d93237321 | 19542bae-778e-4fc8-bcee-3040c06e714f.aac | audio/aac  | 2024-05-03 09:09:10+00 |            | d5617a34-4d00-4285-85fd-19c89baa375b.aac
(1 row)
```

use audio tag https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio to display audio player for it.

You can use this prompt
"
The parameters used were as follows:
    Machine name: M01
    Start time: 2024-04-30 13:30
    End time: 2024-04-30 13:40
    For these parameters, retrieve the relevant vibration data from the database
"
to generate aac file attachment on Likora system.

**Comment by cyrusnej** [comment]
Done
