### ISSUE TITLE
provide AI service changes suggestions window

### ISSUE THREAD

**Issue by asyncfncom** [metric-space-ai/octopus_client#64]
Please add some popup windows that will display additional AI service changes suggestions

I provided a new field in 
https://api.likora.octopus-ai.app/swagger-ui/#/ai_functions/list

"generated_description" it contains description of the function generated by GPT.

Also please add there content of 'parser_feedback' from
https://api.likora.octopus-ai.app/swagger-ui/#/ai_services/read

**Comment by cyrusnej** [comment]
Added
