### ISSUE TITLE
new endpoints for services developers

### ISSUE THREAD

**Issue by asyncfncom** [metric-space-ai/octopus_client#72]
On this endpoint you can download original function body
https://api.likora.octopus-ai.app/swagger-ui/#/ai_services/download_original_function_body

On this one you can download processed funtion body
https://api.likora.octopus-ai.app/swagger-ui/#/ai_services/download_processed_function_body

There is also a diff endpoint - I forgot to update documentation

**Comment by cyrusnej** [comment]
Done
